// Generated by CoffeeScript 1.6.2
(function() {
  require(["vendor/jquery/jquery", "vendor/modernizr/modernizr"], function(jquery, modernizr) {
    var Labs;

    Labs = (function() {
      var afterCatchDom, appendItem, catchDom, dom, events, initialize, showMessges, st, suscribeEvents;

      st = {
        body: 'body',
        squareItem: '#squareItem',
        flipItem: '.f1_container'
      };
      dom = {};
      catchDom = function() {
        dom.body = $(st.body);
        dom.squareItem = $(st.squareItem);
      };
      suscribeEvents = function() {
        $(st.flipItem).on('click', events.flipItem);
      };
      afterCatchDom = function() {
        appendItem();
        showMessges();
      };
      events = {
        flipItem: function() {
          return $(this).addClass('hover');
        }
      };
      showMessges = function() {
        setTimeout(function() {
          return $($(st.flipItem)[1]).trigger('click');
        }, 1000);
        setTimeout(function() {
          return $($(st.flipItem)[2]).trigger('click');
        }, 2000);
        setTimeout(function() {
          return $($(st.flipItem)[3]).trigger('click');
        }, 3000);
        setTimeout(function() {
          return $($(st.flipItem)[4]).trigger('click');
        }, 4000);
        setTimeout(function() {
          return $($(st.flipItem)[5]).trigger('click');
        }, 5000);
        setTimeout(function() {
          return $($(st.flipItem)[14]).trigger('click');
        }, 6000);
        setTimeout(function() {
          return $($(st.flipItem)[15]).trigger('click');
        }, 7000);
        setTimeout(function() {
          return $($(st.flipItem)[16]).trigger('click');
        }, 8000);
        setTimeout(function() {
          return $($(st.flipItem)[25]).trigger('click');
        }, 9000);
        setTimeout(function() {
          return $($(st.flipItem)[26]).trigger('click');
        }, 10000);
        setTimeout(function() {
          return $($(st.flipItem)[27]).trigger('click');
        }, 11000);
        return setTimeout(function() {
          return $($(st.flipItem)[28]).trigger('click');
        }, 12000);
      };
      appendItem = function() {
        var i, screenArea, tmpSquare, totalToAppend;

        screenArea = $(window).width() * $(window).height();
        totalToAppend = Math.round(screenArea / 10000);
        console.log(totalToAppend);
        tmpSquare = dom.squareItem.html();
        i = 0;
        while (i < totalToAppend) {
          dom.body.append(tmpSquare);
          i++;
        }
        $($(st.flipItem)[1]).find('.back').text('F');
        $($(st.flipItem)[2]).find('.back').text('R');
        $($(st.flipItem)[3]).find('.back').text('O');
        $($(st.flipItem)[4]).find('.back').text('N');
        $($(st.flipItem)[5]).find('.back').text('T');
        $($(st.flipItem)[14]).find('.back').text('E');
        $($(st.flipItem)[15]).find('.back').text('N');
        $($(st.flipItem)[16]).find('.back').text('D');
        $($(st.flipItem)[25]).find('.back').text('L');
        $($(st.flipItem)[26]).find('.back').text('A');
        $($(st.flipItem)[27]).find('.back').text('B');
        $($(st.flipItem)[28]).find('.back').text('S');
      };
      initialize = function() {
        catchDom();
        afterCatchDom();
        suscribeEvents();
      };
      return {
        init: initialize
      };
    })();
    return $(document).on('ready', function() {
      return Labs.init();
    });
  });

}).call(this);
